### ISSUE TITLE
Could not load the H20 GBM

### ISSUE THREAD

**Issue by Toon6115** [kaiwaehner/kafka-streams-machine-learning-examples#5]
It shown this error massage when I use java command.

Error: Could not find or load main class com.github.megachucky.kafka.streams.machinelearning.Kafka_Streams_MachineLearning_H2O_GBM_Example

java -cp target/kafka-streams-machine-learning-examples-1.0-SNAPSHOT-jar-with-dependencies.jar com.github.megachucky.kafka.streams.machinelearning.Kafka_Streams_MachineLearning_H2O_GBM_Example

**Comment by Toon6115** [comment]
Solved

**Comment by kaiwaehner** [comment]
Great that you got it working.

I assume you forgot to do the Maven build so that it did not find the (generated) JAR file...

**Comment by Uldanay** [comment]
> It shown this error massage when I use java command.
> 
> Error: Could not find or load main class com.github.megachucky.kafka.streams.machinelearning.Kafka_Streams_MachineLearning_H2O_GBM_Example
> 
> java -cp target/kafka-streams-machine-learning-examples-1.0-SNAPSHOT-jar-with-dependencies.jar com.github.megachucky.kafka.streams.machinelearning.Kafka_Streams_MachineLearning_H2O_GBM_Example

Hello, 
sorry for disturbing, but I have the same problem.
Please, could you share with solution,
Thanks)

**Comment by kaiwaehner** [comment]
@Uldanay Did you do "mvn clean package" successfully? Which Operating System and Java version?
