### ISSUE TITLE
Error on timestamp 

### ISSUE THREAD

**Issue by Toon6115** [kaiwaehner/kafka-streams-machine-learning-examples#6]
Thank you for prompt reply yesterday. Now, I got this error when I send the massage. Here is an error.

Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+. Use a different TimestampExtractor to process this data.

**Comment by kaiwaehner** [comment]
Sounds like you are using a very old version of Apache Kafka? Which version do you use? I tested it with Kafka 1.1. and 2.0.

Pre-0.10 is very old. It did not include timestamps in a message. So it seems to be not compatible.

**Comment by Toon6115** [comment]
Hi kaiwaehner, 

I used the kafka in confluent-5.0.0, and kafka_2.11-2.0.0. It also shown the errors like that.

**Comment by kaiwaehner** [comment]
That's really strange. I will check with Confluent engineers why this can happen with the current version of Kafka and come back to this thread.

**Comment by kaiwaehner** [comment]
Can you please give more details about the steps you do and where this happens?

Are you doing the airline example step-by-step as explained or anything else?
How do you send the message? With kafkacat or another command?

**Comment by kaiwaehner** [comment]
Here is a hint from a colleague if you use kafkacat like in my example:

_Make sure they use librdkafka >= v0.11.4. Old versions of Ubuntu/Debian will have outdated librdkafkas. Verify with `kafkacat -V`_

Maybe this helps.

**Comment by Toon6115** [comment]
Problem solved. I used the kafka producer to send the massage and it work fine.
