### ISSUE TITLE
JUnit test not working in Windows

### ISSUE THREAD

**Issue by jukkakarvanen** [kaiwaehner/kafka-streams-machine-learning-examples#9]
The JUnit test are failing in Windows due to https://issues.apache.org/jira/browse/KAFKA-6647

The same problem seems to be also mentioned here:
https://github.com/kaiwaehner/kafka-streams-machine-learning-examples/issues/4#issuecomment-418805593

Readme also state: "Kafka does not support and work well on Windows, this is not tested at all."

I have used this kind of Workaround to get JUnit tests to work in Windows:
https://github.com/jukkakarvanen/kafka-streams-machine-learning-examples/tree/junit_in_windows

Not sure is this worth merging, but anyway if you want to run test in Windows you can use that branch.

NOTE: This is changed only in test code, not in actual classes.

**Comment by kaiwaehner** [comment]
I merged it. Hopefully https://issues.apache.org/jira/browse/KAFKA-6647 will be fixed soon, then we can remove your workaround and just use the regular Kafka Streams test classes.

As side note: Confluent recommends to NOT use Kafka and especially Kafka Streams on Windows. We have seen several issues and (strange) errors and inconsistencies.

**Comment by jukkakarvanen** [comment]
Yes, currently I am used to develop with IntelliJ IDEA in Windows. Now with this fix you can run the test easily in IDE before launching application inside Docker Linux container.

The application is still failing with exception in cleanup method in Window, but for me it does not matter because I run it inside Docker anyway to avoid the problems you mentioned. 

It would be easy to fix actual application removing the cleanup, because it is only "development time workaround" and to my understanding these examples does not contain anything to cleanup.
